# The name of your Worker. Alphanumeric values and dashes only.
name = "comment-worker"

# The entrypoint/path to the file that will be executed.
main = "./src/index.js"

# Whether you use `<NAME>.<SUBDOMAIN>.workers.dev` to
# test and deploy your Worker.
# @default `true`
workers_dev = true

# A date in the form yyyy-mm-dd, which will be used to determine
# which version of the Workers runtime is used.
compatibility_date = "2023-08-11"

## example config ##
#routes = [
#    { pattern = "comments.zanechua.com", custom_domain = true }
#]
#
[vars]
GITHUB_ORGANIZATION_SLUG = "4gYAagbj"
GITHUB_REPOSITORY_SLUG = "comment-worker"
GITHUB_REPOSITORY_BRANCH = "main"
CW_ALLOWED_ORIGINS = "https://svansr.github.io"
GITHUB_APP_PRIVATE_KEY = "-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAqqpSeltfP85s10SlbcDG/lGce3OIzVjrBhnARKSkJgFl7uG4\ntlWYJ7zmlUEOZvVhuoLSEVzb6VmuAHdEIPjvOo2HCgm6oflWrxr51jgE/eRFmdPt\nHTB/E/Rth+9qTlGDovi4NjucEusCay0ZkAZpPKahTvHGla9e1ROjpveUkdNgplVR\nkUzlt/3gcdSS/hHAL/9RFVNlo0CDw5U1O1E9zxjbF37yg4YGrWmks1IRU6s+5/hK\nbrCJ5Y9cUECvk0iJhn97leqliU/5/L5M4l+Czz73QmprFsxMgtL+2h/rOXXT3Dsr\n+eYVqpRaE5V7CNqvyumgOALJ1dHpvQ48i/DwVwIDAQABAoIBAQChiGBUa1N2Ax3F\nirXBcetnHzurJSlgoz6gIZN35RVw23Xtajv4aH+BbSwaLN9C2BJOBDBsOqXy8ezd\niAU16CgWFYqxF5BMasF/L1s1RQSEgqDV/l65eANvkbRyK0tFIaYkhKFmw3jv9vvt\nEVzWkxrcSyL2o6TAXKK3rsUA7ejzM8AfsLMOCDSZ5MEUnV7UdDKCJm0ZO90oo4UF\nwPBKnlWDVRimas78t8BYItjliLmD7YSjM+a2vft0CxcVMsEl8twSZYX8imm8tYjr\ngsL7JtN+f0jzKv3gCWRUo3JG7/8RhiN6qioWflO5F7eImR/6Dlr7vLFdsBz9YhSZ\nU7H9mudRAoGBAN5nSPtZxhY8TGQRjfNTkRO2ud+ZcFRKVKV6xK1wSf2/vVoskh5D\noj0Wp0OJRo6h5Pg5o/vBTzoN7aB/Ff5iArcI3XKVkQxzb7Oks+U5WnD2stzZHM5m\nm0v+NMjjWUyU0fbVbs6KHG0jz183ajVoA3+R5BIBTJNtQS8VDSiBQFOtAoGBAMRy\nPI3SUXhWFyWvqWLNHa/bQGDesUcQEXE1uzfe6Ohg3SZ88zp8h4b+2s6te/4fhDER\nn6JjLFQEzda5YROpHy9RsKB0fcp7P1BNYLDh6FwA1QnV1hBl135NO+8eIVC+QXiB\nUrz3cREEYdiQJXVwchJb8BDMv4dRIsj0a0+dQPSTAoGBAJIUOSWPE8LrHCnmNdyL\nGRFfxbqOJ+/VWr/OYXyh8peO5ypheCAUwG1rgbWkZwmsYJ6CDamAkS9KkrgGgUWy\nzqG2Wu22O6137PiLx/VZtIPaJiVVHcycLIi/kaAZZEAex8Je8gcLRByTltOtrD8j\n8JhMFQeWftueuV/Zbeka7EuJAoGACqNZDiEOkmKvHDZYCOasreJEqTpGBWAkYaoU\nOmFS4YqlTzlC/q7RtAjHFpwkc82HHhUjPOr78ozUDMW7MRJegvR8iSPlz/o+on2e\nN9Xz/E97Oe4fioHJWqiaD0fla/bxmrH+JgeMUuyW0+BydtqhAseBx5ce5BgLtzAt\nQ4FzjAsCgYBvl7Jh0wWimr7M+MVIzU5vVXXcbFXDUz/HEeJ5iey0OWIpNcbA6qQm\nay+Ra6dmOAYDWT+YmfKwW8KUaabboKYnvh2nGxJ6Jde2ez7DG/El2+OZS0phdgk2\nNxoubRFU30m04pCuFxCelTBww1wFUUt6VXL6ThstcGLxAYrC7bWLsQ==\n-----END RSA PRIVATE KEY-----"
CW_DEBUG = true
GITHUB_APP_ID = 111293932