# The name of your Worker. Alphanumeric values and dashes only.
name = "comment-worker"

# The entrypoint/path to the file that will be executed.
main = "./src/index.js"

# Whether you use `<NAME>.<SUBDOMAIN>.workers.dev` to
# test and deploy your Worker.
# @default `true`
workers_dev = true

# A date in the form yyyy-mm-dd, which will be used to determine
# which version of the Workers runtime is used.
compatibility_date = "2023-08-11"

## example config ##
#routes = [
#    { pattern = "comments.zanechua.com", custom_domain = true }
#]
#
[vars]
GITHUB_ORGANIZATION_SLUG = "4gYAagbj"
GITHUB_REPOSITORY_SLUG = "comment-worker"
GITHUB_REPOSITORY_BRANCH = "main"
CW_ALLOWED_ORIGINS = "https://svansr.github.io"
GITHUB_APP_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDYabChC4wTMC8I\ncS20POAYcmoQ2yoCJO3yhYahiImbkK+uguZBFQ+kcsUNQo5yq/hSk7T07/k2myWs\nFpxOl7e2YLE2yfiS5r0tVT6oRQEzRRF70Mqk5XEoOaEMaRsvhKX9kBwh91UOHuAm\n/09eQo/X95BANTcrWs/P6EO1si4471gcoZGn9L/caHBZ3ASI4usbwhkzf1GA6x0c\n+hDCHyczhAAwEkPG1DZ8bwFwXRvOrFhRVWjkWW36uZbTTfkhH3ls25AIH2sMMl2p\nLrRTRh/girFaaeUbaEj0B+MOeM+QuWNa41UoOFQ23QIYGy01+LJd8QdHJBMvNk7q\nZldX6JCLAgMBAAECggEBAKweKu96upZMPSvur9XokKaA4OC1Hk0ESAcZsYDpkeAb\nC860pyJd+MnmydgI9jg3k9FBTqt77G5EqIqclQZg3ij78BXOPpe/UfgrEyFLeG/p\nX8VkwraxEPVYGEFBmvCJBGeNZQKSrqADaG07o0kpkTPH3n9ik5U0rZECfk+U/fQi\n2TFya5a1ng5/x5lMlqjQ9vDvddy0LCI38PUGvJcJRmGx3STe8CrKFjrjb2cB52h5\n5YiFJJdTXc3D8J/xx/z4Q+T7hJOE2reVXzfmurfX4eoeLBfRSFwZdBIlaEhbzBYi\nzmclt4ocRHQZjbyqQpxyiRNLQqscpck6fxWt6zqBASkCgYEA71Fxh90PfUgTyXKS\nbL5X/w0M2HqoUZ0F9UBWQg1KdwBpQu5/30VKANYj/Q+9eigLFOZIzdnKPBkicxLn\nrqA/QfYiAE929f6fmOgemgZ+vGRT2u7FilixzeRHBzabppNkvzYOU0OMHdEhtXN/\nfMA5uYcd4739kirQVyywHUEWiGUCgYEA53+CRUjQhSdXXhX1zHlzjzn4mYj/RPkO\n6X3NFJAsHrotnqYzzDZ7UWO+kUy9j1HIcSgSwRVGwAw0Fp0tcPOYslekoscQ7sG/\n8LNXLac16tNMgsS/r5lpzBkBEvDtO67TjjlpFaNe8pLAAqGSqSIr/7sUCf1KRk5j\nV+5eoGcQDi8CgYACuWCbdU651Fo1TtKP3lLOGm3tAOhtlWX99q+ErPYOCLkqA+D8\nv6MqA0YBmW5Et7P4lu55OWNt77NOsAZnHHfb3ltguYbXIgDbErlWc4B50IKL2W/y\nNTRA7bpJQLvg14isDId5NymfJURG9nubBe0iSYFzmDQMt+QLOfz/OEBzaQKBgQCF\ngDD+B6nIwBFQPtXLH1cXB9VnpWuguQhyeovkCeiHp9JbJXnFkL25CA6D+H9wwTcY\nmoWGN+DfK6p2SBpGgxRR9N0KykXninBIPQRPXZhoXYZH+3KXr58lhl3qMGp++qkh\n4dXKFrbQqPR2D/tl8kDxb091G07UEKyVru9/DTBjHQKBgQCbFDdLR4HVCNsEuyGO\nkoEa+8lbS1jEQ+QbXM1AbikLfwQuAhqn/qZUo8TKJgekff97c7C/xwPeACQFjoGm\nb10CV2m6ge+Yc9NuVALTNMmk+HLPA86m7bKozvMDT71R+fRrG1h7R5Q5OksjSPu6\n1fVUlLTZXNChHz5WO+dYUEtS6A==\n-----END PRIVATE KEY-----"
CW_DEBUG = true
GITHUB_APP_ID = 2906844