# The name of your Worker. Alphanumeric values and dashes only.
name = "comment-worker"

# The entrypoint/path to the file that will be executed.
main = "./src/index.js"

# Whether you use `<NAME>.<SUBDOMAIN>.workers.dev` to
# test and deploy your Worker.
# @default `true`
workers_dev = true

# A date in the form yyyy-mm-dd, which will be used to determine
# which version of the Workers runtime is used.
compatibility_date = "2023-08-11"

## example config ##
#routes = [
#    { pattern = "comments.zanechua.com", custom_domain = true }
#]
#
[vars]
GITHUB_ORGANIZATION_SLUG = "4gYAagbj"
GITHUB_REPOSITORY_SLUG = "comment-worker"
GITHUB_REPOSITORY_BRANCH = "main"
CW_ALLOWED_ORIGINS = "https://svansr.github.io"
GITHUB_APP_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCqqlJ6W18/zmzX\nRKVtwMb+UZx7c4jNWOsGGcBEpKQmAWXu4bi2VZgnvOaVQQ5m9WG6gtIRXNvpWa4A\nd0Qg+O86jYcKCbqh+VavGvnWOAT95EWZ0+0dMH8T9G2H72pOUYOi+Lg2O5wS6wJr\nLRmQBmk8pqFO8caVr17VE6Om95SR02CmVVGRTOW3/eBx1JL+EcAv/1EVU2WjQIPD\nlTU7UT3PGNsXfvKDhgataaSzUhFTqz7n+EpusInlj1xQQK+TSImGf3uV6qWJT/n8\nvkziX4LPPvdCamsWzEyC0v7aH+s5ddPcOyv55hWqlFoTlXsI2q/K6aA4AsnV0em9\nDjyL8PBXAgMBAAECggEBAKGIYFRrU3YDHcWKtcFx62cfO6slKWCjPqAhk3flFXDb\nde1qO/hof4FtLBos30LYEk4EMGw6pfLx7N2IBTXoKBYVirEXkExqwX8vWzVFBISC\noNX+Xrl4A2+RtHIrS0UhpiSEoWbDeO/2++0RXNaTGtxLIvajpMBcoreuxQDt6PMz\nwB+wsw4INJnkwRSdXtR0MoImbRk73SijhQXA8EqeVYNVGKZqzvy3wFgi2OWIuYPt\nhKMz5ra9+3QLFxUywSXy3BJlhfyKaby1iOuCwvsm035/SPMq/eAJZFSjckbv/xGG\nI3qqKhZ+U7kXt4iZH/oOWvu8sV2wHP1iFJlTsf2a51ECgYEA3mdI+1nGFjxMZBGN\n81ORE7a535lwVEpUpXrErXBJ/b+9WiySHkOiPRanQ4lGjqHk+Dmj+8FPOg3toH8V\n/mICtwjdcpWRDHNvs6Sz5TlacPay3NkczmabS/40yONZTJTR9tVuzoocbSPPXzdq\nNWgDf5HkEgFMk21BLxUNKIFAU60CgYEAxHI8jdJReFYXJa+pYs0dr9tAYN6xRxAR\ncTW7N97o6GDdJnzzOnyHhv7azq17/h+EMRGfomMsVATN1rlhE6kfL1GwoHR9yns/\nUE1gsOHoXADVCdXWEGXXfk077x4hUL5BeIFSvPdxEQRh2JAldXByElvwEMy/h1Ei\nyPRrT51A9JMCgYEAkhQ5JY8TwuscKeY13IsZEV/Fuo4n79Vav85hfKHyl47nKmF4\nIBTAbWuBtaRnCaxgnoINqYCRL0qSuAaBRbLOobZa7bY7rXfs+IvH9Vm0g9omJVUd\nzJwsiL+RoBlkQB7Hwl7yBwtEHJOW062sPyPwmEwVB5Z+2565X9lt6RrsS4kCgYAK\no1kOIQ6SYq8cNlgI5qyt4kSpOkYFYCRhqhQ6YVLhiqVPOUL+rtG0CMcWnCRzzYce\nFSM86vvyjNQMxbsxEl6C9HyJI+XP+j6ifZ431fP8T3s57h+KgclaqJoPR+Vr9vGa\nsf4mB4xS7JbT4HJ22qECx4HHlx7kGAu3MC1DgXOMCwKBgG+XsmHTBaKavsz4xUjN\nTm9VddxsVcNTP8cR4nmJ7LQ5Yik1xsDqpCZrL5Frp2Y4BgNZP5iZ8rBbwpRpptug\npie+HacbEnol17Z7PsMb8SXb45lLSmF2CTY3Gi5tEVTfSbTikK4XEJ6VMHDDXAVR\nS3pVcvpOGy1wYvEBisLttYux\n-----END PRIVATE KEY-----"
CW_DEBUG = true
GITHUB_APP_ID = 111293932